### ISSUE TITLE
cli

### ISSUE THREAD

**Issue by talgautb** [talgautb/typographic-currency-db#1]

**Comment by iamstarkov** [comment]
what did you mean by this issue?

**Comment by talgautb** [comment]
@iamstarkov idea from @drugoi to use it in terminal

**Comment by iamstarkov** [comment]
how?

**Comment by talgautb** [comment]
@iamstarkov i think:
`currencyDB kzt` returns  `₸` and so on

**Comment by iamstarkov** [comment]
fine
