### ISSUE TITLE
another currency db

### ISSUE THREAD

**Issue by iamstarkov** [talgautb/typographic-currency-db#2]
have you seen [currency-formatter/data.js](https://github.com/smirzaei/currency-formatter/blob/master/data.js)?

**Comment by talgautb** [comment]
@iamstarkov yep, most of them is not official

**Comment by iamstarkov** [comment]
i mean you can borrow smth from them or contribute to their project

**Comment by talgautb** [comment]
@iamstarkov ok) if i have time ;)
https://github.com/smirzaei/currency-formatter

**Comment by iamstarkov** [comment]
So did you have time?

**Comment by talgautb** [comment]
@iamstarkov [yep](https://github.com/smirzaei/currency-formatter/pull/11)
