### ISSUE TITLE
PHP replaced by ₱

### ISSUE THREAD

**Issue by denysdovhan** [talgautb/typographic-currency-db#3]
I'm using Textr on my CV page. There are some words about my basic knowledge in PHP. The problem is that [`PHP` is always replaced by `₱`](https://github.com/talgautb/typographic-currency-db/blob/master/index.js#L35). Could you help me?

**Comment by talgautb** [comment]
it is just database, i can't rename Philippines currency :)
i thinks you about [this plugin](https://github.com/talgautb/typographic-currency)
